name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.0.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  intl: ^0.19.0
  intl_utils: ^2.8.10
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  retrofit: ^4.4.0
  rest_client:
    path: packages/rest_client

dev_dependencies:

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_native_splash: ^2.4.6
  retrofit_generator: '>=8.0.0 <10.0.0'

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#  assets:
#    - assets/app

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/app/ic_app.png"
  min_sdk_android: 24

flutter_native_splash:
  android: true
  ios: true
  color: "#304AC1"
  image_android: lib/core/assets/app/ic_app.png
  android_12:
    image: lib/core/assets/app/ic_app.png
  image_ios: lib/core/assets/app/ic_app.png

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: ru
  arb_dir: lib/common/localization/translations
  output_dir: lib/common/localization/generated