name: rest_client
description: Rest client
environment:
  sdk: '^3.7.0'

dependencies:
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  retrofit: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_native_splash: ^2.4.6
  retrofit_generator: '>=8.0.0 <10.0.0'